### ISSUE TITLE
Strange error in auto-update build (zip fields not all same length)

### ISSUE THREAD

**Issue by steven-murray** [conda-forge/21cmfast-feedstock#2]
Issue:

https://github.com/conda-forge/21cmfast-feedstock/pull/1 is failing on Linux builds. Traceback reported is

<details>

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2987, in build_tree
    metadata_tuples = render_recipe(recipe, config=cfg, variants=variants,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 825, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/variants.py", line 554, in get_package_variants
    combined_spec, specs = get_package_combined_spec(recipedir_or_metadata, config=config, variants=variants)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/variants.py", line 523, in get_package_combined_spec
    validate_spec(f, spec)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/variants.py", line 171, in validate_spec
    raise ValueError("Variant configuration errors in {}:\n{}".format(src, "\n".join(errors)))
ValueError: Variant configuration errors in /home/conda/feedstock_root/.ci_support/linux_64_python3.6.____cpython.yaml:
  zip fields in zip_key group ('cdt_name', 'docker_image') are not all the same length
```

</details>

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyrsistent                0.17.3           py38h1e0a361_1    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9              py38h924ce5b_2    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_1    conda-forge
ruamel_yaml               0.15.80         py38h8df0ef7_1003    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
shyaml                    0.6.1                      py_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
su-exec                   0.2               h516909a_1002    conda-forge
tini                      0.18.0            h14c3975_1001    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tqdm                      4.50.2             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.3.1                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.9.0
    conda-build version : 3.20.4
         python version : 3.8.6.final.0
       virtual packages : __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.6 Linux/4.15.0-1096-azure centos/6.10 glibc/2.12
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
</details>

**Comment by steven-murray** [comment]
Fixed with update in conda-forge
